export const judgesData = [
  {
    pj: "55940",
    lastName: "Ogola",
    firstName: "Hon. Eric",
    otherNames: "Kennedy Okumu",
    gender: "MALE",
    email: "eric.ogola@court.go.ke",
    phone: "0722 280 058",
    idNo: "8781595",
    station: "Principal Judge, Milimani Family Division",
    img: "https://judiciary.go.ke/wp-content/uploads/2023/09/F5WNvVZXwAA9jbE-1024x683.jpg",
  },
  {
    pj: "56001",
    lastName: "Korir",
    firstName: "Hon. Roseline",
    otherNames: "C. Langat",
    gender: "FEMALE",
    email: "roseline.korir@court.go.ke",
    phone: "0722 428 139",
    idNo: "7476305",
    station: "Bomet",
    img: "http://highcourt.judiciary.go.ke/wp-content/uploads/2024/11/Hon.-Lady-Justice-Roseline-C.-Lagat-Korir.jpg",
  },
  {
    pj: "14009",
    lastName: "Ougo",
    firstName: "Hon. Rose",
    otherNames: "Edwina",
    gender: "FEMALE",
    email: "rougo@court.go.ke",
    phone: "0722 522 828",
    idNo: "2246656",
    station: "Bungoma",
    img: "http://highcourt.judiciary.go.ke/wp-content/uploads/2024/11/Hon.-Lady-Justice-Rose-Edwina-Atieno-Ougo.jpg",
  },
  {
    pj: "33095",
    lastName: "Kemei",
    firstName: "Hon. David",
    otherNames: "Kipyegomen",
    gender: "MALE",
    email: "dkemei@court.go.ke",
    phone: "0724 787 088",
    idNo: "9778440",
    station: "Bungoma",
    img: "http://highcourt.judiciary.go.ke/wp-content/uploads/2024/11/Hon.-Mr.-Justice-David-Kipyegomen-Kemei.jpg",
  },
  {
    pj: "59326",
    lastName: "Musyoka",
    firstName: "Hon. William",
    otherNames: "Musya",
    gender: "MALE",
    email: "william.musyoka@court.go.ke",
    phone: "0722 499 025",
    idNo: "8365136",
    station: "Busia",
    img: "https://judiciary.go.ke/wp-content/uploads/2024/05/Hon.-Mr.-Justice-Musyoka-William-Musya.png",
  },
  {
    pj: "12926",
    lastName: "Gitari",
    firstName: "Hon. Lucy",
    otherNames: "Waruguru",
    gender: "FEMALE",
    email: "lucy.gitari@court.go.ke",
    phone: "0721 446 084",
    idNo: "5482714",
    station: "Chuka",
    img: "https://judiciary.go.ke/wp-content/uploads/2024/05/Hon.-Lady-Justice-Lucy-Waruguru-Gitari.png",
  },
  {
    pj: "14978",
    lastName: "Nyakundi",
    firstName: "Hon. Reuben",
    otherNames: "Nyambati",
    gender: "MALE",
    email: "rnyakundi@court.go.ke",
    phone: "0722 484 334",
    idNo: "2760750",
    station: "Eldoret",
    img: "https://judiciary.go.ke/wp-content/uploads/2024/05/Hon-Justice-Reuben-Nyakundi.jpg",
  },
  {
    pj: "81735",
    lastName: "Anundo",
    firstName: "Hon. John.R",
    otherNames: "Wananda",
    gender: "MALE",
    email: "wananda.john@court.go.ke",
    phone: "0721 210 501",
    idNo: "13594591",
    station: "Eldoret",
    img: "http://highcourt.judiciary.go.ke/wp-content/uploads/2024/11/Hon.-Justice-John-Robert-Anuro-Wananda.jpg",
  },
  {
    pj: "19871",
    lastName: "Ominde",
    firstName: "Hon. Emily",
    otherNames: "Onyando",
    gender: "FEMALE",
    email: "emily.ominde@court.go.ke",
    phone: "0722756410",
    idNo: "",
    station: "Eldoret",
    img: "https://judiciary.go.ke/wp-content/uploads/2024/05/Hon.-Lady-Justice-Emily-Onyando-Ominde.png",
  },
  {
    pj: "65416",
    lastName: "Njuguna",
    firstName: "Hon. Lucy",
    otherNames: "Mwihaki",
    gender: "FEMALE",
    email: "lucy.njuguna@court.go.ke",
    phone: "0722 757 033",
    idNo: "8989124",
    station: "Embu",
    img: "http://highcourt.judiciary.go.ke/wp-content/uploads/2024/11/Hon.-Lady-Justice-Lucy-Njuguna.jpg",
  },
  {
    pj: "20424",
    lastName: "Onyiego",
    firstName: "Hon. John",
    otherNames: "Nyabuto",
    gender: "MALE",
    email: "john.onyiego@court.go.ke",
    phone: "0722 359 542",
    idNo: "5948626",
    station: "Garissa",
    img: "http://highcourt.judiciary.go.ke/wp-content/uploads/2024/11/Judge-Onyiego.jpeg",
  },
  {
    pj: "14960",
    lastName: "Kiarie",
    firstName: "Hon. Waweru",
    otherNames: "Kiarie",
    gender: "MALE",
    email: "wkiarie@court.go.ke",
    phone: "0722 600 129",
    idNo: "5302738",
    station: "Homabay",
    img: "http://highcourt.judiciary.go.ke/wp-content/uploads/2024/11/Hon.-Justice-Kiarie-Waweru-Kiarie.jpg",
  },
  {
    pj: "20369",
    lastName: "Cherere",
    firstName: "Hon. Thripsisa",
    otherNames: "Wanjiku Wamae",
    gender: "FEMALE",
    email: "thripsisa.wamae@court.go.ke",
    phone: "0733 846 414",
    idNo: "7030464",
    station: "Isiolo",
    img: "http://highcourt.judiciary.go.ke/wp-content/uploads/2024/11/Hon.-Lady-Justice-Cherere-Thripsisa-Wanjiku-Wamae.jpg",
  },
  {
    pj: "20880",
    lastName: "Ngetich",
    firstName: "Hon. Rachel",
    otherNames: "Chepkoech",
    gender: "FEMALE",
    email: "rachael.ngetich@court.go.ke",
    phone: "0722 666 734",
    idNo: "9836966",
    station: "Kabarnet",
    img: "https://judiciary.go.ke/wp-content/uploads/2024/05/JUSTICE-RACHEL-C.-BIOMNDO-NGETICH.jpg",
  },
  {
    pj: "16425",
    lastName: "Mutuku",
    firstName: "Hon. Stella",
    otherNames: "Ngali",
    gender: "FEMALE",
    email: "stella.mutuku@court.go.ke",
    phone: "0727 804 154",
    idNo: "2303343",
    station: "Kajiado",
    img: "http://highcourt.judiciary.go.ke/wp-content/uploads/2024/11/Hon.-Lady-Justice-Stella-Ngali-Mutuku.jpg",
  },
  {
    pj: "20775",
    lastName: "Tamar",
    firstName: "Hon. John",
    otherNames: "Lolwalan",
    gender: "MALE",
    email: "john.tamar@court.go.ke",
    phone: "0726883859",
    idNo: "",
    station: "Kajiado",
    img: "https://example.com/images/20775.jpg",
  },
  {
    pj: "81734",
    lastName: "Chirchir",
    firstName: "Hon. Sophie",
    otherNames: "Chebet",
    gender: "FEMALE",
    email: "sophie.chirchir@court.go.ke",
    phone: "0722 873 874",
    idNo: "10012985",
    station: "Kakamega",
    img: "https://example.com/images/81734.jpg",
  },
  {
    pj: "82774",
    lastName: "Bett",
    firstName: "Hon. Alice",
    otherNames: "Chepngetich",
    gender: "FEMALE",
    email: "alice.soi@court.go.ke",
    phone: "0722301391",
    idNo: "",
    station: "Kakamega",
    img: "https://example.com/images/82774.jpg",
  },
  {
    pj: "21755",
    lastName: "Mbungi",
    firstName: "Hon. Stephen",
    otherNames: "Nzisi",
    gender: "MALE",
    email: "smbungi@court.go.ke",
    phone: "0722270127",
    idNo: "",
    station: "Kakamega",
    img: "https://example.com/images/21755.jpg",
  },
  {
    pj: "10885",
    lastName: "Wendoh",
    firstName: "Hon. Roseline",
    otherNames: "P.V",
    gender: "FEMALE",
    email: "rwendoh@court.go.ke",
    phone: "0733 838 404",
    idNo: "4826632",
    station: "Kapenguria",
    img: "https://example.com/images/10885.jpg",
  },
  {
    pj: "10916",
    lastName: "Karanja",
    firstName: "Hon. Joseph",
    otherNames: "Raphael",
    gender: "MALE",
    email: "joseph.karanja@court.go.ke",
    phone: "0734 760 775",
    idNo: "4826606",
    station: "Kapsabet",
    img: "https://example.com/images/10916.jpg",
  },
  {
    pj: "38841",
    lastName: "Sergon",
    firstName: "Hon. Joseph",
    otherNames: "Kiplagat",
    gender: "MALE",
    email: "joseph.sergon@court.go.ke",
    phone: "0722 654 600",
    idNo: "7233993",
    station: "Kericho",
    img: "https://example.com/images/38841.jpg",
  },
  {
    pj: "55990",
    lastName: "Mwongo",
    firstName: "Hon. Richard",
    otherNames: "Mururu",
    gender: "MALE",
    email: "rmwongo@court.go.ke",
    phone: "0734 594 685",
    idNo: "3490267",
    station: "Kerugoya",
    img: "https://example.com/images/55990.jpg",
  },
  {
    pj: "56027",
    lastName: "Mshila",
    firstName: "Hon. Abigal",
    otherNames: "Shiganga",
    gender: "FEMALE",
    email: "amshila@court.go.ke",
    phone: "0705 132 513",
    idNo: "4826501",
    station: "Kiambu",
    img: "https://example.com/images/56027.jpg",
  },
  {
    pj: "19732",
    lastName: "Chepkwony",
    firstName: "Hon. Dorah",
    otherNames: "Odityo",
    gender: "FEMALE",
    email: "dorah.chepkwony@court.go.ke",
    phone: "0722 745 988",
    idNo: "5793121",
    station: "Kiambu",
    img: "https://example.com/images/19732.jpg",
  },
  {
    pj: "20660",
    lastName: "Kavedza",
    firstName: "Hon. Diana",
    otherNames: "Rachel",
    gender: "FEMALE",
    email: "diana.kavedza@court.go.ke",
    phone: "0724 659 565",
    idNo: "8982813",
    station: "Kibra",
    img: "https://example.com/images/20660.jpg",
  },
  {
    pj: "40140",
    lastName: "Odera",
    firstName: "Hon. Teresia",
    otherNames: "Ochieng",
    gender: "FEMALE",
    email: "teresa.odera@court.go.ke",
    phone: "0722 422 301",
    idNo: "12458164",
    station: "Kisii",
    img: "https://example.com/images/40140.jpg",
  },
  {
    pj: "65238",
    lastName: "Aburili",
    firstName: "Hon. Roselyne",
    otherNames: "Makokha Ekirapa",
    gender: "FEMALE",
    email: "roselyne.aburili@court.go.ke",
    phone: "0715 580 626",
    idNo: "9244251",
    station: "Kisumu",
    img: "https://example.com/images/65238.jpg",
  },
  {
    pj: "81740",
    lastName: "SharifF",
    firstName: "Hon. Mwanaisha",
    otherNames: "Saida",
    gender: "FEMALE",
    email: "mwanaisha.saida@court.go.ke",
    phone: "0720 956 184",
    idNo: "1037911",
    station: "Kisumu",
    img: "https://example.com/images/81740.jpg",
  },
  {
    pj: "65270",
    lastName: "Mrima",
    firstName: "Hon. Antony",
    otherNames: "Charo",
    gender: "MALE",
    email: "antony.murima@court.go.ke",
    phone: "0719 376 886",
    idNo: "11763752",
    station: "Kitale",
    img: "https://example.com/images/65270.jpg",
  },
  {
    pj: "65254",
    lastName: "Limo",
    firstName: "Hon. Robert",
    otherNames: "Kipkoech",
    gender: "MALE",
    email: "robert.limo@court.go.ke",
    phone: "0722 768 866",
    idNo: "9709837",
    station: "Kitui",
    img: "https://example.com/images/65254.jpg",
  },
  {
    pj: "65377",
    lastName: "Otieno",
    firstName: "Hon. Patrick",
    otherNames: "Okwarro",
    gender: "MALE",
    email: "patrick.otieno@court.go.ke",
    phone: "0734 565 357",
    idNo: "8820032",
    station: "Lodwar",
    img: "https://example.com/images/65377.jpg",
  },
  {
    pj: "16522",
    lastName: "Muigai",
    firstName: "Hon. Margaret",
    otherNames: "Waringa",
    gender: "FEMALE",
    email: "margaret.muigai@court.go.ke",
    phone: "0725 901 587",
    idNo: "3642077",
    station: "Machakos",
    img: "https://example.com/images/16522.jpg",
  },
  {
    pj: "81738",
    lastName: "Olel",
    firstName: "Hon. Francis",
    otherNames: "Odhiambo",
    gender: "MALE",
    email: "francis.rayola@court.go.ke",
    phone: "0722 934 875",
    idNo: "13039532",
    station: "Machakos",
    img: "https://example.com/images/81738.jpg",
  },
  {
    pj: "82767",
    lastName: "Inziani",
    firstName: "Hon. Noel",
    otherNames: "Onditi Adagi",
    gender: "FEMALE",
    email: "noel.adagi@court.go.ke",
    phone: "0721241018",
    idNo: "",
    station: "Machakos",
    img: "https://example.com/images/82767.jpg",
  },
  {
    pj: "20694",
    lastName: "Matheka",
    firstName: "Hon. Teresia",
    otherNames: "Mumbua",
    gender: "FEMALE",
    email: "mumbua.matheka@court.go.ke",
    phone: "0720 259 323",
    idNo: "5781166",
    station: "Makueni",
    img: "https://example.com/images/20694.jpg",
  },
  {
    pj: "65385",
    lastName: "Thande",
    firstName: "Hon. Mugure",
    otherNames: "",
    gender: "FEMALE",
    email: "mugure.thande@court.go.ke",
    phone: "0722 336 649",
    idNo: "5598676",
    station: "Malindi",
    img: "https://example.com/images/65385.jpg",
  },
  {
    pj: "20432",
    lastName: "Githinji",
    firstName: "Hon. Stephen",
    otherNames: "Murugu",
    gender: "MALE",
    email: "stephen.githinji@court.go.ke",
    phone: "0727 463 290",
    idNo: "9836209",
    station: "Malindi",
    img: "https://example.com/images/20432.jpg",
  },
  {
    pj: "15013",
    lastName: "Nyaga",
    firstName: "Hon. Jesse",
    otherNames: "Njagi",
    gender: "MALE",
    email: "jesse.nyagah@court.go.ke",
    phone: "0722 610 575",
    idNo: "3665781",
    station: "Marsabit",
    img: "https://example.com/images/15013.jpg",
  },
  {
    pj: "39512",
    lastName: "Muriithi",
    firstName: "Hon. Edward",
    otherNames: "Muthoga",
    gender: "MALE",
    email: "edward.muriithi@court.go.ke",
    phone: "0720 467 361",
    idNo: "732396",
    station: "Meru",
    img: "https://example.com/images/39512.jpg",
  },
  {
    pj: "40181",
    lastName: "Kassan",
    firstName: "Hon. Linus",
    otherNames: "Poghon",
    gender: "MALE",
    email: "linus.kassan@court.go.ke",
    phone: "0720872723",
    idNo: "",
    station: "Meru",
    img: "https://example.com/images/40181.jpg",
  },
  {
    pj: "20555",
    lastName: "Ong'injo",
    firstName: "Hon. Anne",
    otherNames: "C. A. Adwera",
    gender: "FEMALE",
    email: "aonginjo@court.go.ke",
    phone: "0720 886 115",
    idNo: "8295186",
    station: "Migori",
    img: "https://example.com/images/20555.jpg",
  },
  {
    pj: "82775",
    lastName: "Musyoki",
    firstName: "Hon. Benjamin",
    otherNames: "Mwikya",
    gender: "MALE",
    email: "benjamin.musyoki@court.go.ke",
    phone: "0727770135",
    idNo: "",
    station: "Milimani - Anti-Corruption & Economic Crimes",
    img: "https://example.com/images/82775.jpg",
  },
  {
    pj: "59342",
    lastName: "Ngaah",
    firstName: "Hon. Jairus",
    otherNames: "",
    gender: "MALE",
    email: "jairus.ngaah@court.go.ke",
    phone: "0721 435 324",
    idNo: "10006307",
    station: "Milimani – Judicial Review",
    img: "https://example.com/images/59342.jpg",
  },
  {
    pj: "81739",
    lastName: "Chigiti",
    firstName: "Hon. John",
    otherNames: "Mwigumi",
    gender: "MALE",
    email: "john.chigiti@court.go.ke",
    phone: "0714 574 444",
    idNo: "8630574",
    station: "Milimani – Judicial Review",
    img: "https://example.com/images/81739.jpg",
  },
  {
    pj: "15021",
    lastName: "Maina",
    firstName: "Hon. Esther",
    otherNames: "Nyambura",
    gender: "FEMALE",
    email: "esther.maina@court.go.ke",
    phone: "0722 861 229",
    idNo: "3354276",
    station: "Milimani, Anti-Corruption & Economic Crimes",
    img: "https://example.com/images/15021.jpg",
  },
  {
    pj: "33710",
    lastName: "Nangea",
    firstName: "Hon. Julius",
    otherNames: "Mukut",
    gender: "MALE",
    email: "jmukuti@court.go.ke",
    phone: "0726693662",
    idNo: "",
    station: "Milimani, Civil Division",
    img: "https://example.com/images/33710.jpg",
  },
  {
    pj: "82766",
    lastName: "Wanyama",
    firstName: "Hon. Tabitha",
    otherNames: "Ouya",
    gender: "FEMALE",
    email: "tabitha.wanyama@court.go.ke",
    phone: "0722535778",
    idNo: "",
    station: "Milimani, Civil Division",
    img: "https://example.com/images/82766.jpg",
  },
  {
    pj: "43294",
    lastName: "Mkutu",
    firstName: "Hon. Joe",
    otherNames: "Omido",
    gender: "MALE",
    email: "jmkutu@court.go.ke",
    phone: "0722379780",
    idNo: "",
    station: "Milimani, Civil Division",
    img: "https://example.com/images/43294.jpg",
  },
  {
    pj: "12950",
    lastName: "Meoli",
    firstName: "Hon. Christine",
    otherNames: "Wanjiku",
    gender: "FEMALE",
    email: "christine.meoli@court.go.ke",
    phone: "0733 769 314",
    idNo: "966921",
    station: "Milimani, Civil Division",
    img: "https://example.com/images/12950.jpg",
  },
  {
    pj: "65288",
    lastName: "Mulwa",
    firstName: "Hon. Janet",
    otherNames: "Nzilani",
    gender: "FEMALE",
    email: "janet.mulwa@court.go.ke",
    phone: "0721 717 072",
    idNo: "2997784",
    station: "Milimani, Civil Division",
    img: "https://example.com/images/65288.jpg",
  },
  {
    pj: "82770",
    lastName: "Njoroge",
    firstName: "Hon. Benjamin",
    otherNames: "Kimani",
    gender: "MALE",
    email: "benjamin.njoroge@court.go.ke",
    phone: "0725585605",
    idNo: "",
    station: "Milimani, Commercial & Tax",
    img: "https://example.com/images/82770.jpg",
  },
  {
    pj: "61315",
    lastName: "Rutto",
    firstName: "Hon. Rhoda",
    otherNames: "Cherotich",
    gender: "FEMALE",
    email: "rhoda.cherotich@court.go.ke",
    phone: "0721375674",
    idNo: "",
    station: "Milimani, Commercial & Tax",
    img: "https://example.com/images/61315.jpg",
  },
  {
    pj: "81743",
    lastName: "Githiru",
    firstName: "Hon. Freda",
    otherNames: "Mugambi",
    gender: "FEMALE",
    email: "freda.mugambi@court.go.ke",
    phone: "0720 930 342",
    idNo: "14494890",
    station: "Milimani, Commercial Division",
    img: "https://example.com/images/81743.jpg",
  },
  {
    pj: "81737",
    lastName: "Wanyama",
    firstName: "Hon. Nixon",
    otherNames: "Sifuna",
    gender: "MALE",
    email: "nixon.sifuna@court.go.ke",
    phone: "0723 522 005",
    idNo: "10431403",
    station: "Milimani, Commercial Division",
    img: "https://example.com/images/81737.jpg",
  },
  {
    pj: "56019",
    lastName: "Mabeya",
    firstName: "Hon. Alfred",
    otherNames: "",
    gender: "MALE",
    email: "amabeya@court.go.ke",
    phone: "0701 148 657",
    idNo: "10273148",
    station: "Milimani, Commercial Division",
    img: "https://example.com/images/56019.jpg",
  },
  {
    pj: "65369",
    lastName: "Mwangi",
    firstName: "Hon. Margaret",
    otherNames: "Njoki",
    gender: "FEMALE",
    email: "margaret.mwangi@court.go.ke",
    phone: "0722 489 775",
    idNo: "8678899",
    station: "Milimani, Commercial Division",
    img: "https://example.com/images/65369.jpg",
  },
  {
    pj: "81744",
    lastName: "Aleem",
    firstName: "Hon. Visram",
    otherNames: "Alnashir",
    gender: "MALE",
    email: "aleem.visram@court.go.ke",
    phone: "0728 860 230",
    idNo: "28254627",
    station: "Milimani, Commercial Division",
    img: "https://example.com/images/81744.jpg",
  },
  {
    pj: "82773",
    lastName: "Otieno",
    firstName: "Hon. Moses",
    otherNames: "Ado",
    gender: "MALE",
    email: "moses.ado@court.go.ke",
    phone: "0729840559",
    idNo: "",
    station: "Milimani, Commercial Division",
    img: "https://example.com/images/82773.jpg",
  },
  {
    pj: "34059",
    lastName: "Mulwa",
    firstName: "Hon. Peter",
    otherNames: "Mutua",
    gender: "MALE",
    email: "pmulwa@court.go.ke",
    phone: "0735 345 734",
    idNo: "10860647",
    station: "Milimani, Commercial Division",
    img: "https://example.com/images/34059.jpg",
  },
  {
    pj: "81733",
    lastName: "Mongare",
    firstName: "Hon. Josephine",
    otherNames: "Wambua",
    gender: "FEMALE",
    email: "josephine.mongare@court.go.ke",
    phone: "0714 710 782",
    idno: "DK1336",
    station: "Milimani, Commercial Division",
    img: "https://",
    password: "81733",
  },
  {
    pj: "65246",
    lastName: "Mwita",
    firstName: "Hon. Enock",
    otherNames: "Chacha",
    gender: "MALE",
    email: "enock.mwita@court.go.ke",
    phone: "0722 523 440",
    idno: "2827862",
    station: "Milimani, Constitutional & Human rights",
    img: "https://",
    password: "65246",
  },
  {
    pj: "82768",
    lastName: "Mwamuye",
    firstName: "Hon. Andrew",
    otherNames: "Bahati",
    gender: "MALE",
    email: "bahati.mwamuye@court.go.ke",
    phone: "0727333603",
    idno: "",
    station: "Milimani, Constitutional & Human Rights",
    img: "https://",
    password: "82768",
  },
  {
    pj: "34732",
    lastName: "Nthiga",
    firstName: "Hon. Lawrence",
    otherNames: "Mugambi",
    gender: "MALE",
    email: "lawrence.mugambi@court.go.ke",
    phone: "0721 944 911",
    idno: "13176893",
    station: "Milimani, Constitutional & Human rights/ACEC",
    img: "https://",
    password: "34732",
  },
  {
    pj: "55877",
    lastName: "Kimondo",
    firstName: "Hon. George",
    otherNames: "Kanyi",
    gender: "MALE",
    email: "kanyi.kimondo@court.go.ke",
    phone: "0722 510 798",
    idno: "5747091",
    station: "Milimani, Criminal Division",
    img: "https://",
    password: "55877",
  },
  {
    pj: "16394",
    lastName: "Mutende",
    firstName: "Hon. Lilian",
    otherNames: "Nabwire",
    gender: "FEMALE",
    email: "lmutende@court.go.ke",
    phone: "0722 289 962",
    idno: "7921331",
    station: "Milimani, Criminal Division",
    img: "https://",
    password: "16394",
  },
  {
    pj: "82772",
    lastName: "Muteti",
    firstName: "Hon. Alexander",
    otherNames: "Muasya",
    gender: "MALE",
    email: "alexander.muteti@court.go.ke",
    phone: "0723966288",
    idno: "",
    station: "Milimani, Criminal Division",
    img: "https://",
    password: "82772",
  },
  {
    pj: "14156",
    lastName: "Riechi",
    firstName: "Hon. Stephen",
    otherNames: "Nyangau",
    gender: "MALE",
    email: "stephen.riechi@court.go.ke",
    phone: "0722 890 640",
    idno: "378439",
    station: "Milimani, Family Division",
    img: "https://",
    password: "14156",
  },
  {
    pj: "81732",
    lastName: "Nyaundi",
    firstName: "Hon. Patricia",
    otherNames: "Mande",
    gender: "FEMALE",
    email: "patricia.nyaundi@court.go.ke",
    phone: "0721 935 534",
    idno: "9137495",
    station: "Milimani, Family Division",
    img: "https://",
    password: "81732",
  },
  {
    pj: "55966",
    lastName: "Chemitei",
    firstName: "Hon. Hilary",
    otherNames: "Kiplagat",
    gender: "MALE",
    email: "hilary.chemitei@court.go.ke",
    phone: "0722 832 972",
    idno: "9604748",
    station: "Milimani, Family Division",
    img: "https://",
    password: "55966",
  },
  {
    pj: "82769",
    lastName: "Namisi",
    firstName: "Hon. Helen",
    otherNames: "Rafaela",
    gender: "FEMALE",
    email: "helene.namisi@court.go.ke",
    phone: "0733348451",
    idno: "",
    station: "Milimani, Family Division",
    img: "https://",
    password: "82769",
  },
  {
    pj: "52227",
    lastName: "Kendagor",
    firstName: "Hon. Caroline",
    otherNames: "Jepyegen",
    gender: "FEMALE",
    email: "caroline.kendagor@court.go.ke",
    phone: "0722454219",
    idno: "",
    station: "Milimani, Family Division",
    img: "https://",
    password: "52227",
  },
  {
    pj: "13883",
    lastName: "Sewe",
    firstName: "Hon. Olga",
    otherNames: "Akech",
    gender: "FEMALE",
    email: "olga.sewe@court.go.ke",
    phone: "0715 613 828",
    idno: "3981845",
    station: "Mombasa",
    img: "https://",
    password: "13883",
  },
  {
    pj: "40725",
    lastName: "Macharia",
    firstName: "Hon. Florence",
    otherNames: "Wangari",
    gender: "FEMALE",
    email: "florence.wangari@court.go.ke",
    phone: "0722 791 014",
    idno: "20055651",
    station: "Mombasa",
    img: "https://",
    password: "40725",
  },
  {
    pj: "81742",
    lastName: "Mutai",
    firstName: "Hon. Gregory",
    otherNames: "",
    gender: "MALE",
    email: "gregory.mutai@court.go.ke",
    phone: "0720 706 984",
    idno: "13206539",
    station: "Mombasa",
    img: "https://",
    password: "81742",
  },
  {
    pj: "32253",
    lastName: "Andayi",
    firstName: "Hon. Francis",
    otherNames: "Weche",
    gender: "MALE",
    email: "fandayi@court.go.ke",
    phone: "0723016149",
    idno: "",
    station: "Mombasa",
    img: "https://",
    password: "32253",
  },
  {
    pj: "33147",
    lastName: "Ng'arng'ar",
    firstName: "Hon. Julius",
    otherNames: "Kipkosgei",
    gender: "MALE",
    email: "julius.ngarngar@court.go.ke",
    phone: "0721505018",
    idno: "",
    station: "Mombasa",
    img: "https://",
    password: "33147",
  },
  {
    pj: "33192",
    lastName: "Micheni",
    firstName: "Hon. Wendy",
    otherNames: "Kagendo",
    gender: "FEMALE",
    email: "wendy.micheni@court.go.ke",
    phone: "0729338022",
    idno: "",
    station: "Mombasa",
    img: "https://",
    password: "33192",
  },
  {
    pj: "16530",
    lastName: "Githua",
    firstName: "Hon. Cecilia",
    otherNames: "Wathaiya",
    gender: "FEMALE",
    email: "cecilia.githua@court.go.ke",
    phone: "0722 836 324",
    idno: "7320665",
    station: "Muranga",
    img: "https://",
    password: "16530",
  },
  {
    pj: "55924",
    lastName: "Wakiaga",
    firstName: "Hon. James",
    otherNames: "Auodo",
    gender: "MALE",
    email: "james.wakiaga@court.go.ke",
    phone: "0722 683 308",
    idno: "5881101",
    station: "Muranga",
    img: "https://",
    password: "55924",
  },
  {
    pj: "15071",
    lastName: "Nzioka",
    firstName: "Hon. Grace",
    otherNames: "Lidembu",
    gender: "FEMALE",
    email: "grace.nzioka@court.go.ke",
    phone: "0721 217 144",
    idno: "1820480",
    station: "Naivasha",
    img: "https://",
    password: "15071",
  },
  {
    pj: "15869",
    lastName: "Ongudi",
    firstName: "Hon. Hedwig",
    otherNames: "Imbosa",
    gender: "FEMALE",
    email: "hedwig.imbosa@court.go.ke",
    phone: "0722 856 437",
    idno: "569872",
    station: "Nakuru",
    img: "https://",
    password: "15869",
  },
  {
    pj: "20369",
    lastName: "Gichohi",
    firstName: "Hon. Patricia",
    otherNames: "Njeri",
    gender: "FEMALE",
    email: "patricia.gichohi@court.go.ke",
    phone: "0722 769 095",
    idno: "7476281",
    station: "Nakuru",
    img: "https://",
    password: "20369",
  },
  {
    pj: "81736",
    lastName: "Muhochi",
    firstName: "Hon. Samwel",
    otherNames: "Mukira",
    gender: "MALE",
    email: "samwel.mohochi@court.go.ke",
    phone: "0739 649 224",
    idno: "11555865",
    station: "Nakuru",
    img: "https://",
    password: "81736",
  },
  {
    pj: "39928",
    lastName: "Nyaga",
    firstName: "Hon. Heston",
    otherNames: "Mbogo",
    gender: "MALE",
    email: "heston.nyaga@court.go.ke",
    phone: "0722 738 555",
    idno: "11034917",
    station: "Nakuru",
    img: "https://",
    password: "39928",
  },
  {
    pj: "20644",
    lastName: "Ndung'u",
    firstName: "Hon. Anthony",
    otherNames: "Kimani",
    gender: "MALE",
    email: "anthony.ndungu@court.go.ke",
    phone: "0722 704 367",
    idno: "9507563",
    station: "Nanyuki",
    img: "https://",
    password: "20644",
  },
  {
    pj: "59350",
    lastName: "Muthuku",
    firstName: "Hon. Francis",
    otherNames: "Gikonyo",
    gender: "MALE",
    email: "francis.gikonyo@court.go.ke",
    phone: "0721 302 151",
    idno: "8626122",
    station: "Narok",
    img: "https://",
    password: "59350",
  },
  {
    pj: "65262",
    lastName: "Mutungi",
    firstName: "Hon. Charles",
    otherNames: "Kariuki",
    gender: "MALE",
    email: "charles.kariuki@court.go.ke",
    phone: "0721 968 779",
    idno: "3523654",
    station: "Nyahururu",
    img: "https://",
    password: "65262",
  },
  {
    pj: "65408",
    lastName: "Osodo",
    firstName: "Hon. Wilfrida",
    otherNames: "Adhiambo",
    gender: "FEMALE",
    email: "wilfrida.osodo@court.go.ke",
    phone: "0722 679 382",
    idno: "9306730",
    station: "Nyamira",
    img: "https://",
    password: "65408",
  },
  {
    pj: "81741",
    lastName: "Magare",
    firstName: "Hon. Dennis",
    otherNames: "Ng'ono",
    gender: "MALE",
    email: "kizito.magare@court.go.ke",
    phone: "0721 315 628",
    idno: "21358994",
    station: "Nyeri",
    img: "https://",
    password: "81741",
  },
  {
    pj: "13998",
    lastName: "Odero",
    firstName: "Hon. Maureen",
    otherNames: "Akinyi",
    gender: "FEMALE",
    email: "moderoj@court.go.ke",
    phone: "0734 666 583",
    idno: "1868618",
    station: "Nyeri",
    img: "https://",
    password: "13998",
  },
  {
    pj: "10932",
    lastName: "Muya",
    firstName: "Hon. Martin",
    otherNames: "Mati",
    gender: "MALE",
    email: "martin.muya@court.go.ke",
    phone: "0733 724 794",
    idno: "4826631",
    station: "Nyeri",
    img: "https://",
    password: "10932",
  },
  {
    pj: "11904",
    lastName: "Muchemi",
    firstName: "Hon. Florence",
    otherNames: "Nyaguthii",
    gender: "FEMALE",
    email: "florence.muchemi@court.go.ke",
    phone: "0722 707 460",
    idno: "813576",
    station: "Thika",
    img: "https://",
    password: "11904",
  },
  {
    pj: "59334",
    lastName: "Kamau",
    firstName: "Hon. Nancy",
    otherNames: "Jaquline Njuhi",
    gender: "FEMALE",
    email: "nancy.kamau@court.go.ke",
    phone: "0710 220 221",
    idno: "8822013",
    station: "Vihiga",
    img: "https://",
    password: "59334",
  },
  {
    pj: "16239",
    lastName: "Ongeri",
    firstName: "Hon. Asenath",
    otherNames: "Nyaboke",
    gender: "FEMALE",
    email: "asenath.ongeri@court.go.ke",
    phone: "0721 202 908",
    idno: "1592460",
    station: "Voi",
    img: "https://",
    password: "16239",
  },
  {
    pj: "43244",
    lastName: "Omondi",
    firstName: "Hon. Clara",
    otherNames: "Otieno",
    gender: "FEMALE",
    email: "claraotieno23@gmail.com",
    phone: "",
    idno: "",
    station: "High Court",
    img: "https://highcourt.judiciary.go.ke/wp-content/uploads/2025/07/rhc-website-1024x1024.png",
    password: "43244",
  },
  {
    pj: "43211",
    lastName: "Omondi",
    firstName: "Hon. Keith",
    otherNames: "Otieno",
    gender: "MALE",
    email: "denniskeith62@gmail.com",
    phone: "",
    idno: "",
    station: "High Court",
    img: "https://highcourt.judiciary.go.ke/wp-content/uploads/2025/07/rhc-website-1024x1024.png",
    password: "43211",
  },
   {
    pj: "40149",
    lastName: "",
    firstName: "Hon. Terry",
    otherNames: "Odera",
    gender: "FEMALE",
    email: "oderaterry@yahoo.com",
    phone: "",
    idno: "",
    station: "Kisii",
    img: "https://highcourt.judiciary.go.ke/wp-content/uploads/2025/07/rhc-website-1024x1024.png",
    password: "40149",
  },
  {
    pj: "40149",
    lastName: "",
    firstName: "Hon. Terry",
    otherNames: "Odera",
    gender: "FEMALE",
    email: "oderaterry@yahoo.com",
    phone: "",
    idno: "",
    station: "Kisii",
    img: "https://highcourt.judiciary.go.ke/wp-content/uploads/2025/07/rhc-website-1024x1024.png",
    password: "40149",
  },
  {
    pj: "34253",
    lastName: "",
    firstName: "Hon. Francis",
    otherNames: "Andanyi",
    gender: "MALE",
    email: "francis.andanyi@court.go.ke",
    phone: "",
    idno: "",
    station: "Kwale High Court",
    img: "https://highcourt.judiciary.go.ke/wp-content/uploads/2025/07/rhc-website-1024x1024.png",
    password: "34253",
  },
  {
    pj: "12345",
    lastName: "High Court",
    firstName: "Hon. Office of the",
    otherNames: "Registrar",
    gender: "ORHC",
    email: "registrarhighcourt2015@gmail.com",
    phone: "",
    idno: "",
    station: "ORHC",
    img: "https://highcourt.judiciary.go.ke/wp-content/uploads/2025/07/rhc-website-1024x1024.png",
    password: "12345",
  },
];